jb_test_homepage:
    path:     /make/{name}
    defaults: { _controller: JbTestBundle:Default:index }

jb_test_update:
    path:     /update/{id}/{name}
    defaults: { _controller: JbTestBundle:Default:change }
