jb_test_homepage:
    path:     /
    defaults: { _controller: JbTestBundle:Default:index }

jb_test_make:
    path:     /make/
    defaults: { _controller: JbTestBundle:Default:make }

jb_test_update:
    path:     /update/{id}/
    defaults: { _controller: JbTestBundle:Default:change }

jb_test_lock:
    path:     /lock/{id}
    defaults: { _controller: JbTestBundle:Default:lock }
jb_test_unlock:
    path:     /unlock/{id}
    defaults: { _controller: JbTestBundle:Default:unlock }

jb_test_login:
    path: /login
    defaults: { _controller: JbTestBundle:Secured:login }

jb_test_logout:
    path: /logout

jb_test_securitycheck:
    path: /check
    requirements: { _method: POST }

